// Contenido SEO bilingüe de las páginas de servicio (/servicios/<slug>).
// Estructura: campos comunes arriba + bloques `es` / `en`.

export const PROCESO = {
  es: [
    { n: "01", t: "Descubrimiento", d: "Entendemos tu negocio, tu cliente y tus objetivos reales en una llamada corta." },
    { n: "02", t: "Estrategia y propuesta", d: "Definimos alcance, tiempos y precio fijo. Sin sorpresas ni letra chica." },
    { n: "03", t: "Ejecución", d: "Trabajamos con entregas semanales y previews; iteramos con tu feedback." },
    { n: "04", t: "Lanzamiento y soporte", d: "Publicamos, medimos resultados y te acompañamos después del lanzamiento." },
  ],
  en: [
    { n: "01", t: "Discovery", d: "We understand your business, your customer and your real goals in a short call." },
    { n: "02", t: "Strategy & proposal", d: "We define scope, timeline and a fixed price. No surprises, no fine print." },
    { n: "03", t: "Build", d: "We work in weekly deliverables with previews; we iterate with your feedback." },
    { n: "04", t: "Launch & support", d: "We publish, measure results and stick around after launch." },
  ],
};

export const UI = {
  es: {
    breadHome: "Inicio",
    breadServices: "Servicios",
    incluye: "¿Qué incluye?",
    beneficios: "Beneficios",
    proceso: "Cómo trabajamos",
    faq: "Preguntas frecuentes",
    otros: "Otros servicios",
    verServicio: "Ver servicio →",
    ctaQuote: "Cotizar por WhatsApp",
    ctaWork: "Ver trabajos",
    ctaFreeShort: "Cotizá gratis",
    ctaFree: "Cotizá gratis por WhatsApp",
    finalTitle: "¿Listo para empezar?",
    finalText: "Escribinos y te pasamos una cotización gratis para tu proyecto en Colombia.",
    home: "Inicio",
    services: "Servicios",
  },
  en: {
    breadHome: "Home",
    breadServices: "Services",
    incluye: "What's included?",
    beneficios: "Benefits",
    proceso: "How we work",
    faq: "Frequently asked questions",
    otros: "Other services",
    verServicio: "View service →",
    ctaQuote: "Quote on WhatsApp",
    ctaWork: "See work",
    ctaFreeShort: "Free quote",
    ctaFree: "Get a free quote on WhatsApp",
    finalTitle: "Ready to start?",
    finalText: "Message us and we'll send a free quote for your project in Colombia.",
    home: "Home",
    services: "Services",
  },
};

export const SERVICES = [
  {
    slug: "diseno-de-paginas-web",
    icon: "web",
    keywords: ["diseño de páginas web", "diseño web medellín", "creación de páginas web", "desarrollo web colombia", "páginas web medellín"],
    related: ["seo", "publicidad-en-redes-sociales"],
    es: {
      nav: "Diseño de páginas web",
      eyebrow: "Servicio",
      title: "Diseño de Páginas Web en Medellín y Colombia | 2V Digital",
      metaDescription: "Diseño y creación de páginas web profesionales en Medellín y Colombia. Sitios rápidos, responsive y optimizados para convertir visitas en clientes. Cotiza gratis.",
      h1: "Diseño de páginas web que convierten, en Medellín y toda Colombia",
      intro: [
        "En 2V diseñamos y desarrollamos páginas web a medida para empresas y emprendedores en Medellín y toda Colombia. No usamos plantillas genéricas: creamos sitios rápidos, modernos y pensados para vender.",
        "Cada página la construimos con SEO desde el día cero, diseño responsive impecable e integración con WhatsApp, para que tu negocio se vea profesional y convierta visitas en clientes reales.",
      ],
      incluye: [
        { t: "Diseño 100% a medida", d: "Una web única alineada a tu marca, no una plantilla." },
        { t: "Totalmente responsive", d: "Se ve perfecta en celular, tablet y computador." },
        { t: "Optimizada para velocidad", d: "Carga rápida = mejor experiencia y mejor SEO." },
        { t: "SEO desde el día cero", d: "Estructura lista para posicionar en Google." },
        { t: "Integración con WhatsApp", d: "Convierte visitas en conversaciones al instante." },
        { t: "Autogestionable (opcional)", d: "Editá textos e imágenes sin saber programar." },
      ],
      beneficios: [
        { t: "Más credibilidad", d: "Una web profesional genera confianza y cierra más ventas." },
        { t: "Apareces en Google", d: "Te encuentran justo quienes ya buscan lo que ofrecés." },
        { t: "Vende 24/7", d: "Tu mejor vendedor trabajando todos los días del año." },
      ],
      faqs: [
        { q: "¿Cuánto cuesta una página web en Medellín?", a: "Depende del alcance (cantidad de secciones, e-commerce, funcionalidades). Nuestros proyectos arrancan desde un valor accesible y siempre con precio fijo, sin sorpresas. Escribinos por WhatsApp y te pasamos una cotización gratis." },
        { q: "¿Cuánto tarda el desarrollo de la web?", a: "Una landing o web institucional suele tomar de 1 a 3 semanas; proyectos más grandes (e-commerce o software) un poco más. Trabajamos con entregas semanales para que veas el avance." },
        { q: "¿La página va a aparecer en Google?", a: "Sí. Entregamos el sitio con SEO técnico y on-page listo. El posicionamiento orgánico se consolida con el tiempo y se potencia con nuestro servicio de SEO." },
        { q: "¿Puedo editar la web yo mismo?", a: "Sí, si lo querés la dejamos autogestionable para que actualices textos, imágenes y productos sin depender de nadie." },
        { q: "¿Trabajan con clientes fuera de Medellín?", a: "Sí, trabajamos de forma remota con clientes en toda Colombia y LATAM." },
      ],
    },
    en: {
      nav: "Web design",
      eyebrow: "Service",
      title: "Web Design in Medellín & Colombia | 2V Digital",
      metaDescription: "Professional web design and development in Medellín and Colombia. Fast, responsive sites optimized to turn visitors into customers. Get a free quote.",
      h1: "Web design that converts, in Medellín and across Colombia",
      intro: [
        "At 2V we design and build custom websites for companies and founders in Medellín and across Colombia. No generic templates: we create fast, modern sites built to sell.",
        "Every site is built with SEO from day one, flawless responsive design and WhatsApp integration, so your business looks professional and turns visits into real customers.",
      ],
      incluye: [
        { t: "100% custom design", d: "A unique site aligned to your brand, not a template." },
        { t: "Fully responsive", d: "Looks perfect on phone, tablet and desktop." },
        { t: "Speed-optimized", d: "Fast loading = better UX and better SEO." },
        { t: "SEO from day one", d: "Structure ready to rank on Google." },
        { t: "WhatsApp integration", d: "Turns visits into conversations instantly." },
        { t: "Self-manageable (optional)", d: "Edit texts and images without coding." },
      ],
      beneficios: [
        { t: "More credibility", d: "A professional site builds trust and closes more sales." },
        { t: "Show up on Google", d: "Get found by people already searching for you." },
        { t: "Sells 24/7", d: "Your best salesperson, working every day." },
      ],
      faqs: [
        { q: "How much does a website cost in Medellín?", a: "It depends on the scope (number of sections, e-commerce, features). Our projects start at an accessible price, always with a fixed quote and no surprises. Message us on WhatsApp for a free quote." },
        { q: "How long does it take to build?", a: "A landing or company site usually takes 1–3 weeks; larger projects (e-commerce or software) a bit more. We work in weekly deliverables so you see progress." },
        { q: "Will the site show up on Google?", a: "Yes. We ship it with technical and on-page SEO ready. Organic ranking builds over time and is boosted by our SEO service." },
        { q: "Can I edit the site myself?", a: "Yes, if you want we make it self-manageable so you can update texts, images and products on your own." },
        { q: "Do you work with clients outside Medellín?", a: "Yes, we work remotely with clients across Colombia and LATAM." },
      ],
    },
  },
  {
    slug: "seo",
    icon: "search",
    keywords: ["SEO Colombia", "SEO Medellín", "posicionamiento web", "posicionamiento en google", "agencia SEO Medellín"],
    related: ["diseno-de-paginas-web", "publicidad-en-redes-sociales"],
    es: {
      nav: "SEO / Posicionamiento",
      eyebrow: "Servicio",
      title: "SEO en Colombia y Medellín · Posicionamiento Web | 2V Digital",
      metaDescription: "Posicionamiento SEO en Colombia y Medellín. Aparece primero en Google con SEO técnico, on-page, local y de contenidos. Más tráfico orgánico y más clientes.",
      h1: "SEO en Colombia: posiciona tu negocio primero en Google",
      intro: [
        "Hacemos SEO en Medellín y toda Colombia para que tu página aparezca justo cuando tus clientes buscan lo que ofrecés. La mayoría de la gente no pasa de la primera página de Google: nuestro trabajo es ponerte ahí.",
        "Combinamos SEO técnico, optimización on-page, contenidos y SEO local para que ganes visibilidad sostenible en el tiempo, sin depender solo de la publicidad paga.",
      ],
      incluye: [
        { t: "Auditoría SEO inicial", d: "Detectamos qué está frenando tu posicionamiento." },
        { t: "SEO técnico", d: "Velocidad, indexación, estructura y datos estructurados." },
        { t: "SEO on-page", d: "Títulos, contenidos y keywords optimizados por página." },
        { t: "SEO local", d: "Aparece en búsquedas de Medellín y tu ciudad + Google Maps." },
        { t: "Contenidos y blog", d: "Atraemos tráfico con artículos que responden a tu público." },
        { t: "Reportes mensuales", d: "Medimos posiciones, tráfico orgánico y resultados." },
      ],
      beneficios: [
        { t: "Tráfico que no pagás por clic", d: "Visitas constantes sin depender solo de la pauta." },
        { t: "Clientes con intención", d: "Llega gente que ya está buscando comprar." },
        { t: "Resultados que se acumulan", d: "El SEO crece y se sostiene con el tiempo." },
      ],
      faqs: [
        { q: "¿Cuánto tarda el SEO en dar resultados?", a: "El SEO es una inversión a mediano plazo: los primeros movimientos se ven entre 1 y 3 meses, y los resultados sólidos a partir de los 3 a 6 meses, según la competencia de tu sector." },
        { q: "¿Qué es el SEO local?", a: "Es optimizar tu presencia para búsquedas con intención geográfica (ej. 'diseño web Medellín') y para Google Maps / perfil de empresa. Es clave si atendés una zona o ciudad específica." },
        { q: "¿El SEO reemplaza a la publicidad?", a: "Se complementan. La publicidad trae resultados inmediatos; el SEO construye tráfico orgánico sostenible que no pagás por clic. Lo ideal es combinarlos." },
        { q: "¿Hacen SEO en toda Colombia?", a: "Sí, trabajamos SEO para clientes en Medellín, Bogotá, Cali y toda Colombia de forma remota." },
      ],
    },
    en: {
      nav: "SEO / Ranking",
      eyebrow: "Service",
      title: "SEO in Colombia & Medellín · Web Positioning | 2V Digital",
      metaDescription: "SEO and web positioning in Colombia and Medellín. Rank first on Google with technical, on-page, local and content SEO. More organic traffic and more clients.",
      h1: "SEO in Colombia: rank your business first on Google",
      intro: [
        "We do SEO in Medellín and across Colombia so your page shows up right when your customers search for what you offer. Most people never leave the first page of Google: our job is to put you there.",
        "We combine technical SEO, on-page optimization, content and local SEO so you gain sustainable visibility over time, without relying only on paid ads.",
      ],
      incluye: [
        { t: "Initial SEO audit", d: "We find what's holding your ranking back." },
        { t: "Technical SEO", d: "Speed, indexing, structure and structured data." },
        { t: "On-page SEO", d: "Titles, content and keywords optimized per page." },
        { t: "Local SEO", d: "Show up for Medellín searches + Google Maps." },
        { t: "Content & blog", d: "We attract traffic with articles your audience searches." },
        { t: "Monthly reports", d: "We track rankings, organic traffic and results." },
      ],
      beneficios: [
        { t: "Traffic you don't pay per click", d: "Steady visits without relying only on ads." },
        { t: "High-intent clients", d: "Reach people already looking to buy." },
        { t: "Compounding results", d: "SEO grows and holds over time." },
      ],
      faqs: [
        { q: "How long until SEO shows results?", a: "SEO is a mid-term investment: first movements appear in 1–3 months, and solid results from 3–6 months, depending on your industry's competition." },
        { q: "What is local SEO?", a: "It's optimizing your presence for searches with geographic intent (e.g. 'web design Medellín') and Google Maps / business profile. Key if you serve a specific area or city." },
        { q: "Does SEO replace advertising?", a: "They complement each other. Ads bring immediate results; SEO builds sustainable organic traffic you don't pay per click. Best to combine them." },
        { q: "Do you do SEO across Colombia?", a: "Yes, we do SEO for clients in Medellín, Bogotá, Cali and all of Colombia remotely." },
      ],
    },
  },
  {
    slug: "manejo-de-redes-sociales",
    icon: "spark",
    keywords: ["manejo de redes sociales", "community manager medellín", "manejo de redes medellín", "gestión de redes sociales", "redes sociales para empresas"],
    related: ["publicidad-en-redes-sociales", "diseno-de-paginas-web"],
    es: {
      nav: "Manejo de redes sociales",
      eyebrow: "Servicio",
      title: "Manejo de Redes Sociales en Medellín · Community Manager | 2V",
      metaDescription: "Manejo de redes sociales en Medellín y Colombia: estrategia, contenido, diseño, video y community management para Instagram, TikTok y Facebook.",
      h1: "Manejo de redes sociales que hace crecer tu marca",
      intro: [
        "Llevamos el manejo de redes sociales de empresas y emprendedores en Medellín y Colombia. Nos encargamos de la estrategia, el contenido y la comunidad para que tu marca crezca sin pausa, mientras vos te enfocás en tu negocio.",
        "Creamos contenido profesional, constante y con tu identidad, pensado para captar la atención y convertir seguidores en clientes.",
      ],
      incluye: [
        { t: "Estrategia de contenido", d: "Un plan mensual alineado a tus objetivos." },
        { t: "Diseño de publicaciones", d: "Piezas profesionales con tu identidad visual." },
        { t: "Creación y edición de video", d: "Reels y TikToks que enganchan." },
        { t: "Community management", d: "Respondemos y gestionamos tu comunidad." },
        { t: "Calendario y publicación", d: "Constancia sin que tengas que pensarlo." },
        { t: "Reportes mensuales", d: "Crecimiento, alcance e interacción medidos." },
      ],
      beneficios: [
        { t: "Presencia constante", d: "Tu marca activa y profesional todos los días." },
        { t: "Más comunidad", d: "Seguidores reales que interactúan y compran." },
        { t: "Ahorrás tiempo", d: "Nosotros producimos; vos solo aprobás." },
      ],
      faqs: [
        { q: "¿En qué redes trabajan?", a: "Principalmente Instagram, TikTok y Facebook; también LinkedIn según el tipo de negocio." },
        { q: "¿Incluye la creación de contenido?", a: "Sí: estrategia, diseño de piezas, redacción y edición de video. Vos solo revisás y aprobás." },
        { q: "¿Cuánto cuesta el manejo de redes en Medellín?", a: "Tenemos planes mensuales según la cantidad de contenido y redes. Escribinos por WhatsApp y armamos uno a tu medida." },
        { q: "¿Necesito pauta además del manejo?", a: "El manejo hace crecer tu marca de forma orgánica; con publicidad (Meta Ads) acelerás los resultados. Ofrecemos ambos servicios." },
      ],
    },
    en: {
      nav: "Social media management",
      eyebrow: "Service",
      title: "Social Media Management in Medellín · Community Manager | 2V",
      metaDescription: "Social media management in Medellín and Colombia: strategy, content, design, video and community management for Instagram, TikTok and Facebook.",
      h1: "Social media management that grows your brand",
      intro: [
        "We run social media for companies and founders in Medellín and Colombia. We handle strategy, content and community so your brand grows non-stop while you focus on your business.",
        "We create professional, consistent, on-brand content built to grab attention and turn followers into customers.",
      ],
      incluye: [
        { t: "Content strategy", d: "A monthly plan aligned to your goals." },
        { t: "Post design", d: "Professional pieces with your visual identity." },
        { t: "Video creation & editing", d: "Reels and TikToks that hook." },
        { t: "Community management", d: "We reply to and manage your community." },
        { t: "Calendar & posting", d: "Consistency without you thinking about it." },
        { t: "Monthly reports", d: "Growth, reach and engagement measured." },
      ],
      beneficios: [
        { t: "Constant presence", d: "Your brand active and professional every day." },
        { t: "More community", d: "Real followers who engage and buy." },
        { t: "Save time", d: "We produce; you just approve." },
      ],
      faqs: [
        { q: "Which networks do you work with?", a: "Mainly Instagram, TikTok and Facebook; also LinkedIn depending on the business." },
        { q: "Does it include content creation?", a: "Yes: strategy, design, copy and video editing. You just review and approve." },
        { q: "How much does social media management cost in Medellín?", a: "We have monthly plans based on the amount of content and networks. Message us and we'll build one for you." },
        { q: "Do I need ads on top of management?", a: "Management grows your brand organically; with ads (Meta Ads) you accelerate results. We offer both." },
      ],
    },
  },
  {
    slug: "publicidad-en-redes-sociales",
    icon: "spark",
    keywords: ["publicidad en redes sociales", "meta ads colombia", "pauta digital medellín", "publicidad en instagram", "publicidad en facebook"],
    related: ["manejo-de-redes-sociales", "seo"],
    es: {
      nav: "Publicidad en redes sociales",
      eyebrow: "Servicio",
      title: "Publicidad en Redes Sociales (Meta Ads) en Colombia | 2V Digital",
      metaDescription: "Publicidad en redes sociales en Medellín y Colombia: campañas de Meta Ads (Instagram y Facebook) y TikTok Ads para conseguir leads y ventas. Cotiza gratis.",
      h1: "Publicidad en redes sociales que trae clientes",
      intro: [
        "Creamos y gestionamos campañas de publicidad en redes sociales para empresas en Medellín y toda Colombia. Llevamos tu marca a las personas correctas con Meta Ads (Instagram y Facebook) y TikTok Ads.",
        "No se trata de gastar en pauta, sino de invertir: definimos públicos, creativos y mensajes para que cada peso traiga leads y ventas medibles.",
      ],
      incluye: [
        { t: "Estrategia de campañas", d: "Objetivos, públicos y presupuesto bien definidos." },
        { t: "Meta Ads (Instagram + Facebook)", d: "Anuncios optimizados para resultados." },
        { t: "TikTok Ads", d: "Llega a nuevas audiencias donde están." },
        { t: "Diseño de anuncios", d: "Creativos en imagen y video que convierten." },
        { t: "Segmentación precisa", d: "Le hablamos a quien sí te va a comprar." },
        { t: "Optimización y reportes", d: "Mejoramos el rendimiento y te mostramos el retorno." },
      ],
      beneficios: [
        { t: "Resultados rápidos", d: "Tráfico y leads desde los primeros días." },
        { t: "Inversión medible", d: "Sabés cuánto entra por cada peso invertido." },
        { t: "Escalable", d: "Cuando algo funciona, lo amplificamos." },
      ],
      faqs: [
        { q: "¿Cuánto debo invertir en pauta?", a: "Depende de tu objetivo y mercado. Recomendamos un presupuesto mínimo para obtener datos suficientes y te asesoramos según tu caso. La inversión en pauta va aparte de nuestro fee de gestión." },
        { q: "¿En cuánto tiempo veo resultados?", a: "La publicidad trae resultados rápido: las primeras campañas empiezan a generar tráfico y leads en pocos días, y vamos optimizando con los datos." },
        { q: "¿Qué diferencia hay con el manejo de redes?", a: "El manejo construye tu marca de forma orgánica; la publicidad paga acelera el alcance y la captación de clientes. Funcionan mucho mejor juntas." },
        { q: "¿Hacen campañas para toda Colombia?", a: "Sí, configuramos la segmentación geográfica para Medellín, tu ciudad o todo el país." },
      ],
    },
    en: {
      nav: "Social media ads",
      eyebrow: "Service",
      title: "Social Media Ads (Meta Ads) in Colombia | 2V Digital",
      metaDescription: "Social media advertising in Medellín and Colombia: Meta Ads (Instagram and Facebook) and TikTok Ads campaigns to get leads and sales. Get a free quote.",
      h1: "Social media ads that bring clients",
      intro: [
        "We create and manage social media ad campaigns for companies in Medellín and across Colombia. We take your brand to the right people with Meta Ads (Instagram and Facebook) and TikTok Ads.",
        "It's not about spending on ads, it's about investing: we define audiences, creatives and messages so every peso brings measurable leads and sales.",
      ],
      incluye: [
        { t: "Campaign strategy", d: "Clear goals, audiences and budget." },
        { t: "Meta Ads (Instagram + Facebook)", d: "Ads optimized for results." },
        { t: "TikTok Ads", d: "Reach new audiences where they are." },
        { t: "Ad design", d: "Image and video creatives that convert." },
        { t: "Precise targeting", d: "We talk to the people who will buy." },
        { t: "Optimization & reports", d: "We improve performance and show the return." },
      ],
      beneficios: [
        { t: "Fast results", d: "Traffic and leads from the first days." },
        { t: "Measurable investment", d: "You know what comes in per peso invested." },
        { t: "Scalable", d: "When something works, we amplify it." },
      ],
      faqs: [
        { q: "How much should I invest in ads?", a: "It depends on your goal and market. We recommend a minimum budget to get enough data and advise you per case. Ad spend is separate from our management fee." },
        { q: "How soon do I see results?", a: "Ads bring results fast: the first campaigns start generating traffic and leads within days, and we optimize with the data." },
        { q: "How is this different from social media management?", a: "Management builds your brand organically; paid ads accelerate reach and client acquisition. They work much better together." },
        { q: "Do you run campaigns for all of Colombia?", a: "Yes, we set geographic targeting for Medellín, your city or the whole country." },
      ],
    },
  },
  {
    slug: "software-a-medida",
    icon: "code",
    keywords: ["software a medida", "desarrollo de software colombia", "automatización de procesos", "aplicaciones web medellín", "soluciones con IA"],
    related: ["diseno-de-paginas-web", "seo"],
    es: {
      nav: "Software a medida",
      eyebrow: "Servicio",
      title: "Software a Medida en Colombia · Apps y Automatización | 2V",
      metaDescription: "Software a medida en Colombia: aplicaciones web, automatización de procesos, integraciones y soluciones con IA para que tu empresa ahorre tiempo y escale.",
      h1: "Software a medida que le ahorra horas a tu equipo",
      intro: [
        "Desarrollamos software a medida para empresas en Colombia: automatizamos lo repetitivo y creamos herramientas internas que ahorran horas cada semana.",
        "Partimos de tu problema concreto y construimos la solución exacta: apps web, integraciones, dashboards y soluciones con inteligencia artificial.",
      ],
      incluye: [
        { t: "Automatización de procesos", d: "Eliminamos tareas repetitivas y manuales." },
        { t: "Aplicaciones web y de escritorio", d: "Herramientas internas a tu medida." },
        { t: "Soluciones con IA", d: "Chatbots, análisis y asistentes inteligentes." },
        { t: "Integraciones (API REST)", d: "Conectamos tus sistemas y herramientas." },
        { t: "Dashboards y reportes", d: "Tus datos claros para decidir mejor." },
        { t: "Bases de datos", d: "Información ordenada, segura y escalable." },
      ],
      beneficios: [
        { t: "Ahorrás tiempo", d: "Menos trabajo manual, más foco en lo importante." },
        { t: "Menos errores", d: "Los procesos automáticos no se equivocan." },
        { t: "Escala con vos", d: "Soluciones que crecen junto a tu empresa." },
      ],
      faqs: [
        { q: "¿Qué tipo de software desarrollan?", a: "Apps web internas, automatizaciones, integraciones entre sistemas, dashboards, soluciones con IA y más. Siempre partimos de tu problema concreto." },
        { q: "¿Cómo cobran un software a medida?", a: "Con cotización personalizada según el alcance. Primero entendemos tu necesidad y te pasamos una propuesta con alcance y precio claros." },
        { q: "¿Trabajan con empresas fuera de Medellín?", a: "Sí, desarrollamos de forma remota para empresas en toda Colombia y el exterior." },
      ],
    },
    en: {
      nav: "Custom software",
      eyebrow: "Service",
      title: "Custom Software in Colombia · Apps & Automation | 2V",
      metaDescription: "Custom software in Colombia: web apps, process automation, integrations and AI solutions so your company saves time and scales.",
      h1: "Custom software that saves your team hours",
      intro: [
        "We build custom software for companies in Colombia: we automate the repetitive and create internal tools that save hours every week.",
        "We start from your concrete problem and build the exact solution: web apps, integrations, dashboards and AI-powered solutions.",
      ],
      incluye: [
        { t: "Process automation", d: "We remove repetitive, manual tasks." },
        { t: "Web & desktop apps", d: "Internal tools built for you." },
        { t: "AI solutions", d: "Chatbots, analytics and smart assistants." },
        { t: "Integrations (REST API)", d: "We connect your systems and tools." },
        { t: "Dashboards & reports", d: "Your data clear to decide better." },
        { t: "Databases", d: "Organized, secure and scalable information." },
      ],
      beneficios: [
        { t: "Save time", d: "Less manual work, more focus on what matters." },
        { t: "Fewer errors", d: "Automated processes don't make mistakes." },
        { t: "Scales with you", d: "Solutions that grow with your company." },
      ],
      faqs: [
        { q: "What kind of software do you build?", a: "Internal web apps, automations, system integrations, dashboards, AI solutions and more. We always start from your concrete problem." },
        { q: "How do you charge for custom software?", a: "With a custom quote based on scope. First we understand your need and send a proposal with clear scope and price." },
        { q: "Do you work with companies outside Medellín?", a: "Yes, we develop remotely for companies across Colombia and abroad." },
      ],
    },
  },
];

export function getService(slug) {
  return SERVICES.find((s) => s.slug === slug) || null;
}

// Etiquetas del submenú de "Servicios" en el nav (bilingüe).
export const SERVICE_MENU = SERVICES.map((s) => ({
  slug: s.slug,
  label: { es: s.es.nav, en: s.en.nav },
}));
